version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: renovate/yarn:1.22
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-fb2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Dependencies package installation
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: root-fb2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Testing
          command: yarn test-auto
      - run:
          name: Build
          command: yarn build
workflows:
  test-build-deployment:
    jobs:
      - test
