version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    docker:
      - image: hadmarine/docker-environments:ubuntu20-node16-1.0.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setting yarn version to berry
          command: yarn set version berry
      - restore_cache:
          keys:
            - root-fb2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Dependencies package installation
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: root-fb2-dependencies-{{ checksum "package.json" }}
      - run:
          name: .env decryption
          command: yarn quickcert.js decrypt -k $QCERT_ENV
      - run:
          name: Testing
          command: yarn test-auto
      - run:
          name: Build
          command: yarn build
workflows:
  test-build-deployment:
    jobs:
      - test
